### PR TITLE
 Cleanup panicking test threads

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
Depends on #322.

Updates  #321.

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
There seems to be a race condition in the `oneshot_multi_thread_send_close_stress` test. In a loop it creates two threads, on one thread it drops the receiver and on the other thread it send a value, which means that sending sometimes succeeds and sometimes fails. @stjepang any ideas on what would be the best way forward?

**Comment by stjepang** [comment]
Looks like that test makes is nonsensical. I'd say let's just pull `tx.send(1)` out of `assert_eq!(tx.send(1), Err(SendError(1)))` - so remove the assert but keep the send operation.

And add a comment on top of the file saying "Remove assertion from `oneshot_multi_thread_send_close_stress`."

**Comment by Thomasdezeeuw** [comment]
Fixed the race condition and added the change to the list.

**Comment by stjepang** [comment]
lgtm, thanks!! :)

bors r+

**Pull request merged**
