### PR TITLE
Add initial docs to crossbeam-skiplist

### PR DESCRIPTION
**Pull request by caelunshun**
As per https://github.com/crossbeam-rs/crossbeam/issues/503#issuecomment-631679442, I'm writing the docs for `crossbeam-skiplist`. 

Checklist:
* [x] Crate-level docs
* [x] Docs for `SkipMap`
* [ ] Docs for `SkipSet`

I also have some thoughts about the API:
* `Entry`'s name is misleading; it's not the same as the standard library's map entry API. A name like `Ref` might be more suitable, to align with `RefCell`. 
* `set::Entry` could implement `Deref<Target=T>` for convenience. 
* I see the base `SkipList` struct is exposed, though I'm not sure if it belongs in the public API.

### CODE REVIEW

**Comment by stjepang** [comment]
This is amazing work <3 

`Entry` is a lot like the new linked list `Cursor`: https://doc.rust-lang.org/nightly/alloc/collections/linked_list/struct.Cursor.html

The idea behind `SkipList` is that it is a low-level API for people who want more control than what `SkipSet` and `SkipMap` offer. I believe @Amanieu is using it.

**Comment by Amanieu** [comment]
`SkipList` is exposed because it is usable in `no_std` code. It does not rely on the thread-local `Collector` (since `no_std` doesn't have TLS).

**Comment by taiki-e** [comment]
Hi @caelunshun! Any updates on this? (It seems that there is still one checkbox left.)

If you don't have the bandwidth to work on the remaining things, I'd like to leave them to follow-up PR (by me or someone) and merge this to avoid conflicts.

BTW, this looks great. Thanks for working on this!

**Review by taiki-e — APPROVED** [review]
Thanks @caelunshun for working on this!

I added the remaining things to the checklist of the tracking issue (crossbeam-rs/crossbeam#635).

(It's been a month since the previous comment, so I'll merge it.)
bors r+

**Pull request merged**
