### PR TITLE
Conversion of Parker/Unparker into/from a raw pointer

### PR DESCRIPTION
**Pull request by stjepang**
@carllerche Can you review this PR and confirm the API fits your use case?

### CODE REVIEW

**Comment by carllerche** [comment]
@stjepang I believe this does, but won't get back to this until later this week. Feel free to ship before then, or you can wait until I can test it.

**Comment by carllerche** [comment]
I used the impl [here](https://github.com/tokio-rs/tokio/blob/std-future/tokio-executor/src/park.rs#L229-L268) (untested as of yet). wdyt?

**Comment by dekellum** [comment]
Has it been sufficiently tested by now, on tokio master since June 24?   I'm asking only because the patch for this branch there (master branch tokio-executor, for crossbeam-utils only) is a bit of a liability for future updates to crossbeam.

**Comment by jeehoonkang** [comment]
I don't know whether it's still relevant to Tokio, but I think the PR itself is okay.  If no one is objecting, I'll merge this 3 days later.

**Pull request merged**
