### PR TITLE
Port test from Go lang - goroutines

### PR DESCRIPTION
**Pull request by itarato**
Porting the [goroutines](https://github.com/golang/go/blob/master/test/chan/goroutines.go) test from the Go lang repository.

Part of https://github.com/crossbeam-rs/crossbeam/issues/201

Any help would be appreciated.

### CODE REVIEW

**Comment by itarato** [comment]
Fixing the test failure.

**Comment by stjepang** [comment]
Thank you!!

bors r+

**Comment by itarato** [comment]
CI complains about:

```
test channel_tests::stress_recv_timeout_shared ... error: process didn't exit successfully: `/home/travis/build/crossbeam-rs/crossbeam/target/debug/deps/mpsc-861f81d284a630b3 --test-threads=1` (signal: 11, SIGSEGV: invalid memory reference)
```

Not sure if related. Shall I rebase with latest master? Or other advice?

**Comment by stjepang** [comment]
Oh wow that seems like an unrelated bug! Fortunately, I think I know where the problem is and have submitted a fix: https://github.com/crossbeam-rs/crossbeam/pull/382

Let's try merging this PR again:

bors r+

**Pull request merged**
