### PR TITLE
Rustfmt everything

### PR DESCRIPTION
**Pull request by stjepang**

### CODE REVIEW

**Comment by Vtec234** [comment]
Thoughts on taking this opportunity to add `rustfmt --check` to Travis as a lint that must pass? That way we can avoid 'Rusfmt everything' to be the latest commit for every file :P

**Comment by stjepang** [comment]
@Vtec234 Sure, let's give it a shot!

**Comment by Vtec234** [comment]
`rustfmt` could have failed due to missing `cargo fmt`, since it's not installed by default by `rustup`.

**Comment by stjepang** [comment]
Thanks for fixing this! :)
bors r+

**Pull request merged**
