### PR TITLE
Change crossbeam-channel's license to MIT OR Apache-2.0

### LINKED ISSUE #536: AND license in crossbeam_channel
Hi, I see that in #419 issues with AND usage of licenses were at least partly addressed and the master branch now has a license expressed as `MIT AND BSD-2-Clause OR Apache-2.0 AND BSD-2-Clause`.

I'm opening this ticket in the context of adding a dependency to crossbeam channel in [webrender](https://github.com/servo/webrender/), for use Firefox. We have to somewhat meticulous about licenses. I am not personally well versed in the topic, so I will mostly quote the feedback I got at the license approval review:

"MIT AND BSD-2-Clause" is somewhat reasonable, but that's only because there's vanishingly little difference between the MIT and BSD-2 licenses: MIT implies some freedoms BSD-2 is explicit about, and that's just about it. Using OR here would not change the situation here significantly.

"Apache-2.0 AND BSD-2-Clause" is a problematic construct: Apache 2.0 provides explicit patent liability protection and the BSD-2-clause explicitly says you get no such protection.

Quoting from the conclusion of the license approval review: "If we're going to pull this in while staying compliant with the licenses involved we should ask upstream to either pick one or "OR" two, and we definitely don't want to permit "AND" as an acceptable predicate in our licensing logic because that way lies madness."

What particular guarantees do you mean to express through the current license? would it be possible to simplify it into `MIT OR Apache-2.0 OR BSD-2-Clause`?

### PR DESCRIPTION
**Pull request by nical**
Fixes #536 

Was there breaking changes since the last published versions? it looks like it was 5 months ago so it sounds likely. If so I suspect you'll want to wait for other potential changes before making a `0.5` release, would it be possible to create a 0.4 branch and change publish the license update there on top of `0.4.2`'s revision?

That would allow me to use crossbeam-channel in WebRender.

### CODE REVIEW

**Comment by nical** [comment]
The CI doesn't provide much information about the failing tests. They had been pending for a long long time so I suppose the backlog was just canceled/timed-out at some point.

**Comment by stjepang** [comment]
Published a new patch version of crossbeam-channel that includes this PR.

**Comment by nical** [comment]
Thanks a lot !

**Comment by taiki-e** [comment]
Hm, the `master` branch was supposed to contain breaking changes... But does the compile seem to succeed?

Either way, I think we need to create the `v0.7` branch and backport this and publish a new version of crossbeam-channel. (0.4.3 has [UB](https://github.com/crossbeam-rs/crossbeam/issues/539) (there is no UB in versions 0.4.2 or less), and [adding default-feature](https://github.com/crossbeam-rs/crossbeam/commit/208bda7b796141b061749ce05dbecedf7908965a) is technically a breaking change)
(I did the same thing in crossbeam-queue before, but I pushed only [the tag](https://github.com/crossbeam-rs/crossbeam/releases/tag/crossbeam-queue-0.2.3) without pushing the branch; https://github.com/crossbeam-rs/crossbeam/issues/523#issuecomment-642347864)

**Comment by taiki-e** [comment]
Published crossbeam-channel v0.4.4, and yanked crossbeam-channel v0.4.3.

**Pull request merged**
