### PR TITLE
Run Miri on CI

### PR DESCRIPTION
**Pull request by taiki-e**

### CODE REVIEW

**Comment by taiki-e** [comment]
crossbeam-channel test takes about an hour, so I'll reduce iterations more... (other crates are okay)

**Comment by taiki-e** [comment]
blocked on #613

**Comment by taiki-e** [comment]
This has encountered the same ICE as https://github.com/rust-lang/miri/issues/1643 and is blocked until an update of miri.

**Comment by RalfJung** [comment]
> This has encountered the same ICE as [rust-lang/miri#1643](https://github.com/rust-lang/miri/issues/1643) and is blocked until an update of miri.

Oh, I entirely forgot to bump the submodule! Feel free to ping me if this happens in the future.
https://github.com/rust-lang/rust/pull/80758 will bring that fix to the distributed Miri.

**Comment by jeehoonkang** [comment]
@taiki-e LGTM.  Please feel free to let bors merge it.

**Comment by taiki-e** [comment]
It seems some tests hang when using the latest Miri.

**Comment by RalfJung** [comment]
Interesting, maybe something in crossbeam changed and now it's running into https://github.com/rust-lang/miri/issues/1388?

**Comment by taiki-e** [comment]
I'm not sure. Most of the commits after January 1st were written by me, but I don't think there were relevant changes for the crossbeam-deque that hang occurred.

**Comment by taiki-e** [comment]
I *guess* it's related to https://github.com/rust-lang/miri/pull/1686, but currently I don't have the bandwidth to investigate it.

**Comment by RalfJung** [comment]
Good point. You could run Miri with `-Zmiri-compare-exchange-weak-failure-rate=0` to check this.

**Comment by taiki-e** [comment]
@RalfJung Thanks. I'll try it.

**Comment by taiki-e** [comment]
Hmm, it seems `-Zmiri-compare-exchange-weak-failure-rate=0.0` doesn't fix hang. https://github.com/crossbeam-rs/crossbeam/pull/578/checks?check_run_id=1940042095

Currently, miri is unavailable on the latest nightly, so I'll try again once https://github.com/rust-lang/rust/pull/82253 is merged.

**Pull request merged**
