### PR TITLE
Upgrade to autocfg 1

### PR DESCRIPTION
**Pull request by cuviper**

### CODE REVIEW

**Comment by jeehoonkang** [comment]
Thanks!  bors r+

**Comment by cuviper** [comment]
Thanks! Any chance you could publish point releases? (i.e. before the next semver bump)

**Comment by jonhoo** [comment]
Yeah, a patch bump of these would be awesome!

**Comment by jonhoo** [comment]
@jeehoonkang Any chance we might see a point release with this change?

**Pull request merged**
