### PR TITLE
Remove #[allow(unsafe_code)] from select! macro

### LINKED ISSUE #405: Unable to use select macro in #![forbid(unsafe_code)] environments
## Description

I am using `#![forbid(unsafe_code)]` in my crate and for a while I only had a single `recv()` inside of a select macro and everything was compiling fine.

When I added a second `recv()` arm it failed to compile.

I switched to using the `Select` struct for now and it compiles and works properly.

I expected the `select!` macro to only use the safe API of `Select`, not emitting unsafe code inside the macro.

## Example code

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=efee4be440204c5c160827d5fa1de5fb

### PR DESCRIPTION
**Pull request by taiki-e**
Replaces #430 

Closes #405

### CODE REVIEW

**Comment by stjepang** [comment]
Hmmm, why is this failing on Travis CI? Does this require a newer version of the compiler?

**Comment by taiki-e** [comment]
The behavior on which this PR depends is introduced in rust-lang/rust#52467 and has been available since 1.29.

**Comment by taiki-e** [comment]
(Personally, I think it's fine to postpone the fix of #405 until the minimum supported version is 1.29+.)

**Comment by extrawurst** [comment]
when is that 

> (Personally, I think it's fine to postpone the fix of #405 until the minimum supported version is 1.29+.)

@taiki-e  when is that gonna be ?

**Comment by stjepang** [comment]
@taiki-e Feel free to merge this PR if you think it's ready!

**Pull request merged**
