### PR TITLE
Update README.md of crossbeam epoch to have correct version requirement of rust compiler

### PR DESCRIPTION
**Pull request by TotalKrill**

### CODE REVIEW

**Comment by taiki-e** [comment]
This is not correct. It is the *old nightly* compiler that is not supported; the *stable* compiler is supported in all versions since 1.36. See also https://github.com/crossbeam-rs/crossbeam/issues/803.

**Comment by TotalKrill** [comment]
Well, It doesnt build on stable now, so I don't know how you can say that stable 1.36 is supported?

**Comment by taiki-e** [comment]
Our CI (which runs daily) makes sure crossbeam-* crates can build on stable 1.36, latest stable (currently 1.59), and latest nightly): https://github.com/crossbeam-rs/crossbeam/actions/runs/2031722592

> It doesnt build on stable now

Hmm, that's odd. Can you provide the full error message and the version of rustc (`rustc -vV`)? Also, under what situations did you get the error? (CLI or editor, CI or local, native or WSL, etc.)

**Comment by TotalKrill** [comment]
Never mind me, I was so sure I was running stable by default, turns out some script I have used changed to an older version of nightly by default. 

So basically, my system was wrongly configured and I was mistaken.

**Pull request closed without merging**
