### PR TITLE
Prevent drift in tick delivery (fix #406)

### LINKED ISSUE #406: channel::tick() behavior questions
Hello !
When using `channel::tick::recv()` I expected it to compute its time to sleep with some kind of `Instant` saved at the time of the `Channel` instantiation.
Instead the `Instant` used is the one taken from the last message received, which has two effects :
- it guarantees that the specified duration at least elapses between two messages received
- it leads to a small shift from the initial `Channel` instantiation Instant, mostly due to the job scheduler not waking up the thread necessarily on time

If this was intended originally, then some documentation about the second effect is necessary.
If this is a bug, I would be happy to send a PR. However we must keep in mind that some users might rely on the first effect above.

_Also, I think the `channel::tick::recv` should not have to loop around a `thread::sleep` as the latter already guarantees to sleep **at least** the provided duration, which leaves room for simplifying this file a lot._

### PR DESCRIPTION
**Pull request by drrlvn**
Calculate the next delivery time based on the previous one instead of the time the thread awoke, preventing a small but noticeable drift from accumulating.

### CODE REVIEW

**Comment by drrlvn** [comment]
I fixed the tests so they now pass. I don't know why the CI fails on 1.26/1.28, maybe it's a dependency issue. This is the error:
```
error[E0432]: unresolved import `self::std::hint`

  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:13:16

   |

13 | use self::std::hint::unreachable_unchecked;

   |                ^^^^ Could not find `hint` in `std`

error: aborting due to previous error
```

**Comment by drrlvn** [comment]
> I don't know why the CI fails on 1.26/1.28, maybe it's a dependency issue. 

Happens on `master` as well, see #412.

**Comment by stjepang** [comment]
Hey, thank you for submitting this PR and apologies for coming to it so late! :( I'm assuming you already forgot about this code so I submitted a new PR: #456

I think `try_recv()` should not change - the drift there is intended and this is exactly how tickers work in Go, too. However, we do need changes in `recv()` - instead of sleeping and then attempting to receive a message, we should receive it first and *then* sleep.

**Comment by drrlvn** [comment]
@stjepang OK, great, I'll close this PR then. Thanks!

**Pull request closed without merging**
