### PR TITLE
Add Receiver::new_sender and Sender::new_receiver

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
I've added some basic tests, let me know if it need more extensive tests. I'm also not sure the changes I've made are sufficient or if they also need changes inside the various flavours.

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
The CI failure seems to be unrelated.

**Comment by BurntSushi** [comment]
Could you say more about what the use case for these methods is?

**Comment by Thomasdezeeuw** [comment]
I have a use case where I'm holding a `Receiver` and a `Sender` in the same structure, where the `Sender` is only used to be cloned and shared. Since both are a pointer to the same structure it just wastes memory. I'm also using thousands of these structures so even small reductions add up.

**Comment by Thomasdezeeuw** [comment]
Are there are reviewers available for this? I really need this feature.

**Comment by taiki-e** [comment]
Seems this needs to clarify what happens when called after the channel is disconnected.

**Comment by Thomasdezeeuw** [comment]
This has taken too long and I've moved on to using a different crate.

**Pull request closed without merging**
