### PR TITLE
Bump parking_lot

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by Eijebong** [comment]
Would be nice to get a crossbeam-channel release with that so that I could update parking_lot in servo :)

**Comment by stjepang** [comment]
Thanks!

bors r+

**Comment by bluss** [comment]
@stjepang  crossbeam needs a bump too, right now it depends on two different versions of parking_lot (directly and through channel)

**Comment by stjepang** [comment]
@bluss Published a new version with bumped dependencies.

**Comment by bluss** [comment]
Thanks!

**Pull request merged**
