### PR TITLE
Separate licenses with `OR` instead of `/`

### LINKED ISSUE #419: Invalid license identifiers
The license identifiers found in the Cargo.toml look like `MIT/Apache-2.0` and `MIT/Apache-2.0 AND BSD-2-Clause` but `/` is not valid in SPDX. I'm assuming that `MIT OR Apache-2.0` is what is intended. I'd provide a pull request but I'm not sure whether the BSD case needs to be `(MIT OR Apache-2.0) AND BSD-2-Clause` or `MIT OR Apache-2.0 AND BSD-2-Clause`

### PR DESCRIPTION
**Pull request by taiki-e**
`/` is deprecated. 

Refs: https://github.com/rust-lang/cargo/pull/4898

Closes #419

### CODE REVIEW

**Comment by taiki-e** [comment]
Hm, I should also update license badges in readmes.

**Comment by jeehoonkang** [comment]
Thanks!

bors r+

**Comment by taiki-e** [comment]
bors r=jeehoonkang

Rebased.

**Comment by taiki-e** [comment]
bors retry

**Comment by jeehoonkang** [comment]
This PR must not be the reason of the CI failure.  I reported the CI failure at #514, and I'm merging it manually...

**Pull request merged**
